heat_template_version: 2013-05-23

description: yaml file for region - RegionOne

resources:
  nova_flavor:
    properties:
      disk: 322
      ephemeral: 0
      extra_specs: {'aggregate_instance_extra_specs:nv': 'true', 'hw:cpu_policy': dedicated,
        'hw:mem_page_size': large, 'hw:numa_nodes': '2'}
      flavorid: 9ad64bf609cd4737a30430998b41267a
      is_public: true
      name: nv.c3r10d322.n0
      ram: 10240
      rxtx_factor: 1
      swap: 0
      tenants: []
      vcpus: 3
    type: OS::Nova::Flavor

outputs:
  nova_flavor_id:
    value: {get_resource: nova_flavor}
